#+TITLE: [メモ]LinuxのCPU使用率について
#+DATE: 2014-08-29
#+SETUPFILE: ~/.emacs.d/blogs/octopress/setupfile.org
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: linux
#+JEKYLL_TAGS: vmstat, iowait
#+JEKYLL_COMMENTS: true
#+JEKYLL_PUBLISHED: true

現場にリダーが「ディスクI/O待ちの時間もCPU使用率にカウントされる」と言っています、
自分心の中では「それはないだろう」と疑いましたが、そのばで反論しなかったけど。
まぁ自信がない性格でもありますから。

事後にこっそり調べることにした。

{{{more}}}

* IO待ち情報整理
iowaitは、 CPUがアイドル状態で、システムに未処理のディスク入出力要求があった時間の割合
を意味しますが、iowaitの状態であれば、CPUを必要とするプロセスが他にある場合には、その
プロセスがCPUを使用することが可能です。つまり、iowaitが98%であってもCPUの負荷が高い状
態ではありません。一般的に、usとsyの列の値を足した値をCPU使用率と見ます。

* IO処理の詳細
プロセスから =read/write= システムコール発行したらコンテキストスイッチが発生してプロ
セスの状態が =TASK_UNINTERRUPTIBLE= へ遷移します。

- TASK_UNINTERRUPTIBLE: 割り込み不可な状態、ディスクI/Oの完了待ち

プロセスが =TASK_UNINTERRUPTIBLE= 状態にいる時間がiowaitにカウントされる感じかな？

* idleとiowaitのカウント処理
=linux-3.12/kernel/sched/cputime.c=
#+begin_src c
/*
 * Account for idle time.
 * @cputime: the cpu time spent in idle wait
 */
void account_idle_time(cputime_t cputime)
{
	u64 *cpustat = kcpustat_this_cpu->cpustat;
	struct rq *rq = this_rq();

	if (atomic_read(&rq->nr_iowait) > 0)                       ★runキューにio待ちしているプロセスであるかの判定
		cpustat[CPUTIME_IOWAIT] += (__force u64) cputime;      ★iowait時間の集計
	else
		cpustat[CPUTIME_IDLE] += (__force u64) cputime;        ★idle時間の集計
}
#+end_src

* vmstatからCPU使用率を確認する

IOを起こすコマンド
#+begin_example
[akira@hakusai ~]$ dd if=/dev/zero of=test.001 bs=800K count=10000
^C807+0 レコード入力
807+0 レコード出力
661094400 バイト (661 MB) コピーされました、 10.508 秒、 62.9 MB/秒
#+end_example

CPU使用率の確認
#+begin_example
[akira@jizai ~]$ vmstat 1 10
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs    us sy id wa st
 1  0 1425060 169948  13772 474992   18   47   168   138  146  428    3  1 92  4  0
 0  0 1424824 169824  13772 474912  312    0   312     0  542 1601    2  0 96  2  0
 1  2 1426728 100300  13656 546416  164 2164   172 142596  914 33073  1  4 55 41  0  ★IOを起こすコマンドを実行した
 0  7 1435552  97376  13656 555764  108 8880   220 82160  798 1474    0  5 22 72  0
 0  6 1441460  86464  13612 570636  144 6036   604 32936 7117 1854    3  3 21 73  0
 0  5 1446688 120264  13620 545976   36 5304  1868 51384 1148 1148    1  2  9 88  0
 0  5 1454492  86352  13620 589772  136 8052   136 84852 1108 1803    1  7 10 82  0
 0  6 1464232 102028  13624 583412   32 9868    32 71820  772 1728    1  5 10 84  0
 0  6 1479288 125716  13632 568468  116 15248   116 73964 1175 2030   1  2 12 86  0
 0  6 1482776 111212  13636 590008  452 3856   452 36624 1518 4672    1  3 20 76  0
[akira@jizai ~]$
#+end_example

前述より、 =us= と =sy= がCPUの使用率を示しているので、この状態ではIO待ちが高いけど、
CPU負荷が低いことでしょう。

* cpuwaitの用語の誤解
CPU Waitは単純にCPUを待っていると理解してはいけません、


* 参考
- [[http://d.hatena.ne.jp/yohei-a/20120201/1328108666][iowait について]]
